apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-bigip1-ctlr-deployment
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: k8s-bigip-ctlr
  replicas: 1
  template:
    metadata:
      name: k8s-bigip-ctlr
      labels:
        app: k8s-bigip-ctlr
    spec:
      serviceAccountName: k8s-bigip-ctlr
      containers:
        - name: k8s-bigip-ctlr
          image: "f5networks/k8s-bigip-ctlr:latest"
          #imagePullPolicy: IfNotPresent
          imagePullPolicy: Always
          env:
            - name: BIGIP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: bigip-login
                  key: username
            - name: BIGIP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bigip-login
                  key: password
          command: ["/app/bin/k8s-bigip-ctlr"]
          args: [
            "--bigip-username=$(BIGIP_USERNAME)",
            "--bigip-password=$(BIGIP_PASSWORD)",
            "--bigip-url=10.1.1.1",
            "--bigip-partition=AS3",
            #"--namespace=default",
            "--insecure=true",
            "--pool-member-type=cluster",
            "--manage-ingress=false",
            "--log-level=debug"
            #"--agent=as3"
            ]
