apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: monitoring
spec:
  type: LoadBalancer
  loadBalancerIP: 10.5.0.29
  ports:
  - port: 9090
    targetPort: 9090
  selector:
    app: prometheus-server
