kind: ConfigMap
apiVersion: v1
metadata:
  name: f5-as3-amctrl3
  namespace: istio-system
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
        "class": "AS3",
        "declaration": {
            "class": "ADC",
            "schemaVersion": "3.10.0",
            "id": "urn:uuid:33045210-3ab8-4636-9b2a-c98d22ab915d",
            "label": "http",
            "remark": "Simple HTTP application with RR pool",
            "Common": {
               "class": "Tenant",
               "Shared": {
                 "class": "Application",
                 "template": "shared",
                 "XFF_HTTP_Profile": {
                 "class": "HTTP_Profile",
                 "xForwardedFor": true
                 }
               }
            },
            "AMCTRL3": {
                "class": "Tenant",
                "amctrl3_app": {
                    "class": "Application",
                    "template": "generic",
                    "amctrl3_ingress": {
                        "class": "Service_HTTP",
                        "virtualAddresses": [
                            "10.12.0.20"
                        ],
                        "virtualPort": 19001,
                        "remark":"ingress: Aspen Mesh Dashboard ingress",
                        "pool": "amctrl3_pool",
                        "profileHTTP":{"use": "/Common/Shared/XFF_HTTP_Profile"}
                    },
                    "amctrl3_pool": {
                        "class": "Pool",
                        "monitors": [
                            "http"
                        ],
                        "members": [
                            {
                                "servicePort": 19001,
                                "shareNodes": true,
                                "serverAddresses": []
                            }
                        ]
                    }
               }
            }
        }
    }
